services:
  postgres:
    image: postgres:17
    container_name: airline-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - airline_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.27
    container_name: airline-liquibase
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/liquibase/changelog   
    command:
      - --search-path=/liquibase/changelog
      - --changeLogFile=changelog-master.yaml
      - --url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update

volumes:
  airline_data: